# gitops/apps/clustersecretstore/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clustersecretstore
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR-ORG/project5-gitops
    targetRevision: main
    path: manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: external-secrets.io
      kind: ClusterSecretStore
      jsonPointers:
        - /metadata/annotations
