# Frontend infrastructure values - managed by Terraform
# digest is managed by the application repo workflow (build-and-push action or update-digest-only)

image:
  repository: "864546685796.dkr.ecr.us-east-1.amazonaws.com/project-5-dev-frontend"
  digest: "sha256:83e398cb29e50286fe4cd1269b030f8f8d57fb5ebd72c7f9667106dcb6eb6c25"
  tag: ""
  pullPolicy: Always

namespace:
  name: frontend
  create: false

service:
  type: "ClusterIP"
  port: 80

serviceAccount:
  create: false
  name: frontend-sa

containerPort: 80

ingress:
  enabled: true
  host: "frontend-app.project-5.projects-devops.cfd"
  ingressControllerClassResourceName: "alb"
  ingressPath: "/"
  annotations:
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/group.name: "project-5-dev-alb-shared-group"
    #SG list order argo,frontend,backend
    alb.ingress.kubernetes.io/security-groups: "sg-0a400c2d8a2c57f3d,sg-0b37604b29878c999,sg-0d60d2f081060880c"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:864546685796:certificate/de5834b9-59e1-4a02-8184-54e7c028cab6"
    # External DNS annotation (optional - helps external-dns identify the record)
    external-dns.alpha.kubernetes.io/hostname: "frontend-app.project-5.projects-devops.cfd"

# External Secrets  
externalSecrets:
  enabled: true
  externalSecretName: frontend-app-secrets
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  remoteKey: "project-5-dev-frontend-envs"
  #targetSecretName: frontend-env

secretStore:
  enabled: true
  name: "aws-secretsmanager"
  service: "SecretsManager"
  region: "us-east-1"
  serviceAccountName: "frontend-sa"
  syncWave: "-1"